### PR TITLE
adjusted users migration to the changes in profile model

### PR DESCRIPTION
**Pull request by shtayeb**

### CODE REVIEW

**Comment by shtayeb** [comment]
@aleemcahn Please review this.

**Review by aleemcahn — CHANGES_REQUESTED** [review]
Run the migration script to test it out. If successful then good to go.
Also refactor the code for name in users module in the following places.

- views/register_view
- views/profile
- forms/ProfileUpdateForm
- forms/ProfileUpdateForm
- templates/profile

Check for other places as well if it is referenced somewhere.

**Comment by shtayeb** [comment]
@aleemcahn  No need to refactor for name.

The name property is available in the Profile model.

**Comment by aleemcahn** [comment]
@shtayeb please check these, you'll see and know what to do, I am concatenating the first_name and last_name there, which you already handled with property, so, no longer need for the one i am doing.  

views/register_view
views/profile
forms/ProfileUpdateForm
forms/ProfileUpdateForm

**Comment by shtayeb** [comment]
@aleemcahn Done.

**Pull request merged**
